# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: forbid-new-submodules
-   repo: https://github.com/realm/SwiftLint/
    rev: 0.47.0
    hooks:
    -   id: swiftlint
        args: ["--fix"]
    -   id: swiftlint
        args: ["--strict"]
-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.49.7
    hooks:
    -   id: swiftformat
-   repo: https://github.com/crate-ci/typos/
    rev: v1.5.0
    hooks:
    -   id: typos-src
        args: ["--format", "brief"]
